### ISSUE TITLE
Can we get a new release on crates.io?

### ISSUE THREAD

**Issue by johanneskoester** [adumbidiot/lz-str-rs#11]
Hi! We need the code in the master branch quite urgently, would you be so kind to release a new version on crates.io?

Thanks,
Johannes

**Comment by adumbidiot** [comment]
Unfortunately, I do not control the [lz-string](https://crates.io/crates/lz-string) crate on crates.io. I can rename this library and publish it there if needed. Is there any name that would be convenient for you?

**Comment by fxwiegand** [comment]
We need to release a new version of [rust-bio-tools](https://github.com/rust-bio/rust-bio-tools) but cannot until we change the git dependency to a regular one, so I think publishing under a different name would be great. Just to throw something in the room: `lz-str`, `lz-string-compression` or `lzs` would be available. But I think @johanneskoester is the expert when it comes to good naming.

**Comment by johanneskoester** [comment]
Any name would be fine. Personally, I'd like lz-str or rust-lz-string most.

**Comment by adumbidiot** [comment]
I think I'll go with lz-str in that case.

**Comment by adumbidiot** [comment]
I've released this crate under https://crates.io/crates/lz-str.

**Comment by fxwiegand** [comment]
> I've released this crate under https://crates.io/crates/lz-str.

Thanks a lot!
